name: soiltrack_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  toastification: ^2.3.0
  http: ^1.3.0
  permission_handler: ^10.0.0
  wifi_scan: ^0.4.1+1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #LIST OF LOGO
    - assets/logo/DARK HORIZONTAL.png
    - assets/logo/DARK VERTICAL.png
    - assets/logo/LIGHT HORIZONTAL.png
    - assets/logo/LIGHT VERTICAL.png

    #ELEMENTS
    - assets/elements/microchip.png
